apiVersion: v1
kind: Service
metadata: 
  name: cricketer-info-service
spec: 
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
      nodePort: 30200
  type: NodePort
  selector:
    app: cricketer-info